"""
transcript.py
Handles: extracting a YouTube video ID from any URL format,
and fetching the transcript/caption text (timed segments) for that video.

Primary source: youtube-transcript.ai (free, no key, not IP-blocked).
Fallback source: yt-dlp directly (works if the free service is ever down).
"""

import re
import os
import json
import urllib.request
import urllib.error
import yt_dlp

COOKIE_PATH = "/tmp/yt_cookies.txt"


def extract_video_id(url: str) -> str | None:
    """
    Pulls the 11-character YouTube video ID out of any common URL format:
    - https://www.youtube.com/watch?v=VIDEOID
    - https://youtu.be/VIDEOID
    - https://www.youtube.com/watch?v=VIDEOID&t=30s
    - https://m.youtube.com/watch?v=VIDEOID
    - https://www.youtube.com/shorts/VIDEOID
    Returns None if no valid ID pattern is found.
    """
    if not url:
        return None

    patterns = [
        r"(?:youtube\.com/watch\?v=)([a-zA-Z0-9_-]{11})",
        r"(?:youtu\.be/)([a-zA-Z0-9_-]{11})",
        r"(?:youtube\.com/shorts/)([a-zA-Z0-9_-]{11})",
        r"(?:youtube\.com/embed/)([a-zA-Z0-9_-]{11})",
        r"(?:youtube\.com/live/)([a-zA-Z0-9_-]{11})",
    ]

    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)

    return None


# ---------------------------------------------------------------------------
# Primary source: youtube-transcript.ai
# ---------------------------------------------------------------------------

_TIMESTAMP_LINE_RE = re.compile(r"^\[(\d+):(\d{2})(?::(\d{2}))?\]\s*(.*)$")


def _timestamp_to_seconds(mm_or_hh: str, ss: str, extra_ss: str | None) -> float:
    """
    Converts a [M:SS] or [H:MM:SS] style timestamp into total seconds.
    """
    if extra_ss is not None:
        # Format was [H:MM:SS]
        hours = int(mm_or_hh)
        minutes = int(ss)
        seconds = int(extra_ss)
        return hours * 3600 + minutes * 60 + seconds
    else:
        # Format was [M:SS] or [MM:SS]
        minutes = int(mm_or_hh)
        seconds = int(ss)
        return minutes * 60 + seconds


def _parse_transcript_ai_text(raw_text: str) -> list:
    """
    Parses the markdown-ish response from youtube-transcript.ai into our
    segments shape: [{"text": ..., "start": ..., "duration": ...}, ...]

    Expected format includes lines like:
        [0:01] Some spoken text here...
        [0:31] More text...
    with a header before the "## Transcript" line and a footer after
    the final "---" that we ignore.
    """
    lines = raw_text.splitlines()

    # Only look at content after the "## Transcript" marker, if present.
    if "## Transcript" in raw_text:
        start_idx = next(
            (i for i, line in enumerate(lines) if line.strip() == "## Transcript"),
            0,
        )
        lines = lines[start_idx + 1:]

    raw_segments = []
    for line in lines:
        line = line.strip()
        if not line or line == "---":
            continue
        if line.startswith("Generated by"):
            continue

        match = _TIMESTAMP_LINE_RE.match(line)
        if not match:
            continue

        mm_or_hh, ss, extra_ss, text = match.groups()
        start_seconds = _timestamp_to_seconds(mm_or_hh, ss, extra_ss)
        text = text.strip()
        if text:
            raw_segments.append({"start": start_seconds, "text": text})

    if not raw_segments:
        return []

    # Compute a rough duration for each segment as the gap to the next one.
    segments = []
    for i, seg in enumerate(raw_segments):
        if i + 1 < len(raw_segments):
            duration = max(raw_segments[i + 1]["start"] - seg["start"], 1.0)
        else:
            duration = 30.0  # best guess for the final segment
        segments.append(
            {"text": seg["text"], "start": seg["start"], "duration": duration}
        )

    return segments


def _fetch_from_transcript_ai(video_id: str) -> dict:
    """
    Tries to fetch the transcript from youtube-transcript.ai.
    Returns {"success": True, "segments": [...]} or {"success": False, "error": ...}
    """
    url = f"https://youtube-transcript.ai/transcript/{video_id}.txt"

    try:
        req = urllib.request.Request(
            url, headers={"User-Agent": "Mozilla/5.0 (Prism transcript fetcher)"}
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw_text = resp.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        return {"success": False, "error": f"youtube-transcript.ai returned HTTP {e.code}"}
    except Exception as e:
        return {"success": False, "error": f"youtube-transcript.ai request failed: {str(e)}"}

    segments = _parse_transcript_ai_text(raw_text)

    if not segments:
        return {"success": False, "error": "youtube-transcript.ai returned no parseable segments."}

    return {"success": True, "segments": segments}


# ---------------------------------------------------------------------------
# Fallback source: yt-dlp
# ---------------------------------------------------------------------------


def _prepare_cookie_file() -> str | None:
    """
    If the YT_COOKIES env var is set (full Netscape cookies.txt contents),
    write it to a temp file and return the path. Otherwise return None.
    """
    raw = os.environ.get("YT_COOKIES", "").strip()
    if not raw:
        return None

    try:
        if "\\n" in raw and "\n" not in raw:
            raw = raw.replace("\\n", "\n")
        with open(COOKIE_PATH, "w", encoding="utf-8") as f:
            f.write(raw + "\n")
        return COOKIE_PATH
    except Exception:
        return None


def _parse_json3_captions(raw_bytes: bytes) -> list:
    """
    Parses YouTube's json3 caption format into our segments shape.
    """
    data = json.loads(raw_bytes.decode("utf-8"))
    segments = []

    for event in data.get("events", []):
        if "segs" not in event:
            continue
        text = "".join(seg.get("utf8", "") for seg in event["segs"]).strip()
        if not text:
            continue
        start_ms = event.get("tStartMs", 0)
        duration_ms = event.get("dDurationMs", 0)
        segments.append(
            {
                "text": text,
                "start": start_ms / 1000.0,
                "duration": duration_ms / 1000.0,
            }
        )

    return segments


def _build_ydl_opts(client: str, cookie_file: str | None) -> dict:
    opts = {
        "skip_download": True,
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ["en"],
        "quiet": True,
        "no_warnings": True,
        "extractor_args": {"youtube": {"player_client": [client]}},
    }
    if cookie_file:
        opts["cookiefile"] = cookie_file
    return opts


def _fetch_from_yt_dlp(video_id: str) -> dict:
    """
    Fallback transcript fetch using yt-dlp directly. Same logic as before,
    used only when youtube-transcript.ai fails.
    """
    url = f"https://www.youtube.com/watch?v={video_id}"
    cookie_file = _prepare_cookie_file()
    clients = ["android", "ios", "mweb", "web"]

    info = None
    ydl_used = None
    last_error = "Unknown error."

    for client in clients:
        try:
            ydl = yt_dlp.YoutubeDL(_build_ydl_opts(client, cookie_file))
            info = ydl.extract_info(url, download=False)
            ydl_used = ydl
            break
        except Exception as e:
            last_error = str(e)
            info = None
            continue

    if not info:
        hint = ""
        if "not a bot" in last_error or "Sign in" in last_error:
            hint = (
                " YouTube is blocking this server's IP. "
                "Set the YT_COOKIES environment variable to fix this."
            )
        return {"success": False, "error": f"yt-dlp fallback failed: {last_error}{hint}"}

    subs = info.get("subtitles", {}).get("en") or info.get("automatic_captions", {}).get("en")
    if not subs:
        return {"success": False, "error": "No transcript/caption available for this video."}

    track = next((s for s in subs if s.get("ext") == "json3"), None)
    if not track:
        return {"success": False, "error": "No json3 caption track available for this video."}

    caption_url = track.get("url")
    if not caption_url:
        return {"success": False, "error": "Caption track had no URL."}

    try:
        raw = ydl_used.urlopen(caption_url).read()
        segments = _parse_json3_captions(raw)
    except Exception as e:
        return {"success": False, "error": f"Failed to download/parse captions: {str(e)}"}

    if not segments:
        return {"success": False, "error": "Transcript came back empty."}

    return {"success": True, "segments": segments}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def fetch_transcript(video_id: str) -> dict:
    """
    Fetches the transcript for a video ID.

    Tries youtube-transcript.ai first (fast, not IP-blocked). If that fails
    for any reason, falls back to yt-dlp directly (with cookies if
    YT_COOKIES is set).

    Returns:
        {"success": True, "segments": [{"text": ..., "start": ..., "duration": ...}, ...]}
    or:
        {"success": False, "error": "<reason>"}
    """
    if not video_id:
        return {"success": False, "error": "Invalid or missing video ID."}

    primary_result = _fetch_from_transcript_ai(video_id)
    if primary_result["success"]:
        return primary_result

    fallback_result = _fetch_from_yt_dlp(video_id)
    if fallback_result["success"]:
        return fallback_result

    return {
        "success": False,
        "error": (
            f"Transcript fetch failed. "
            f"Primary source error: {primary_result['error']} | "
            f"Fallback source error: {fallback_result['error']}"
        ),
    }


def format_transcript_for_prompt(segments: list, chunk_seconds: int = 30) -> str:
    """
    Converts raw transcript segments into readable chunks with timestamp
    markers, instead of dumping hundreds of tiny fragments into the prompt.

    Groups consecutive segments into ~chunk_seconds-second blocks, each
    prefixed with [start_seconds], so Gemini/Groq has real time-anchors
    to build the valuable_timeline output accurately.
    """
    if not segments:
        return ""

    chunks = []
    current_chunk_text = []
    current_chunk_start = segments[0]["start"]

    for seg in segments:
        if seg["start"] - current_chunk_start >= chunk_seconds and current_chunk_text:
            chunks.append(
                f"[{int(current_chunk_start)}s] " + " ".join(current_chunk_text)
            )
            current_chunk_text = []
            current_chunk_start = seg["start"]

        current_chunk_text.append(seg["text"].strip())

    if current_chunk_text:
        chunks.append(f"[{int(current_chunk_start)}s] " + " ".join(current_chunk_text))

    return "\n".join(chunks)


if __name__ == "__main__":
    test_url = "https://www.youtube.com/watch?v=mvod11IL-Zc"
    vid = extract_video_id(test_url)
    print("Extracted video ID:", vid)

    result = fetch_transcript(vid)
    if result["success"]:
        print(f"Got {len(result['segments'])} segments.")
        print(format_transcript_for_prompt(result["segments"])[:500])
    else:
        print("Error:", result["error"])